services:
  authentication: #authentication service
    container_name: authentication
    build:
      dockerfile: authentication/Dockerfile
      context: .
    restart: always
    ports:
      - "80:80"
    environment:
      - JWT_KEY=${JWT_KEY}

  service1-api: #service1 service
    container_name: service1
    build:
      dockerfile: service1/Dockerfile
      context: .
    restart: always
    environment:
      - JWT_KEY=${JWT_KEY}
    ports:
      - "81:81"
    depends_on:
      - authentication